version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/html:ro
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./app:/var/www/html
      - db_data:/var/www/html/database
    environment:
      - PHP_DATABASE_PATH=/var/www/html/database/database.sqlite
      
volumes:
  db_data: